### ISSUE TITLE
update crop damage data

### ISSUE THREAD

**Issue by chayserie** [chayserie/cdct#10]
-create function for updating crop damage data
-as much as possible use the same form for add to avoid redundant script?

**Comment by renielcanlas** [comment]
Check pull request #12

**Comment by chayserie** [comment]
done creating function for updating crop damage data but with minor bugs such as:
1. Error in changing pages from update to add damage.
2. after taking photos for first data, the second data get those pictures if you did not capture photo for the second data.
3. dynamic select box error (change the value)

**Comment by chayserie** [comment]
task done for updating crop damage data
1. finished page changes issues from add form to update form
2.done update data in database.
3. 2&3 issue not yet resolve.
4.update listview after update bug

**Comment by renielcanlas** [comment]
To reset select options, use this.
`$("select option").removeAttr("selected");`
`$("select").selectmenu("refresh",true);`

**Comment by renielcanlas** [comment]
Reset the filename for the picture box by resetting the data-attributes. 
`$("#t1").attr('data-filename', '');`
`$("#t2").attr('data-filename', '');`

**Comment by renielcanlas** [comment]
also, add the form reset codes inside the 
`$("addcrop").click();` 
function
