### ISSUE TITLE
checkbox dynamic

### ISSUE THREAD

**Issue by chayserie** [chayserie/cdct#15]
` $('input[type=checkbox]').prop('checked', false).checkboxradio('refresh');`  
this part is my code for removing the checked on the check box (under refresh form function)
-bugs:
-value of checkbox always on even not checked
`$("#wind").is( "checked",true );
false
$("#wind").is( "checked",false );
false`
-it always return false even the checkbox is checked
`$("#wind").val();
"on"`and return on even the checkbox is not cheked

**Comment by chayserie** [comment]
put checkbox for owner name (if the owner is same as the farmer name)
-checkbox for farmer address(if the farmer address same as the farm location)

**Comment by renielcanlas** [comment]
do not use `.val();` to get the value, use 
`if($("#wind").prop('checked')){
value="true";
}else{
value="false";
}`

**Comment by chayserie** [comment]
close the first comment (issue regarding wind and flood checkboxes)
