### ISSUE TITLE
Dynamic Places

### ISSUE THREAD

**Issue by renielcanlas** [chayserie/cdct#2]
Generate functionality to make dynamic places
- Load Municipalities based on chosen province
- Load Brgys based on chosen municipality

**Comment by renielcanlas** [comment]
@chayserie Please find a way to integrate prepopulated databases in cordova, since JSON data is too slow.

**Comment by renielcanlas** [comment]
@chayserie  Can we close this issue now?

**Comment by chayserie** [comment]
ok
