### ISSUE TITLE
Document .on event not working

### ISSUE THREAD

**Issue by chayserie** [chayserie/cdct#5]
@renielcanlas 
`document.on("swiperight");`

I want to have swipe event on my listview data

**Comment by renielcanlas** [comment]
I think this one is just misplaced, you can check my code part on

#3 
**cdct.js Line: 294-299**
`$(document).on("swiperight swipeleft", "#croplist li", function(e){
		 if(confirm("Delete this record?\nFarmer: " + $(this).find("h2").text())){
			alert("Deleted (but not realy)");
			//Execute SQL Delete command here
		 }
	 });`
